fix: update documentation workflow to correctly prepare and check for coverage report

diff --git a/.github/workflows/docs-and-testcov.yml b/.github/workflows/docs-and-testcov.yml
--- a/.github/workflows/docs-and-testcov.yml
+++ b/.github/workflows/docs-and-testcov.yml
@@ -30,8 +30,7 @@ jobs:
   
       - name: Prepare documentation for Pages
         run: |
-          mkdir -p docs
-          cp -r target/doc/* docs/
+
 
       - name: Install Cargo binstall
         uses: cargo-bins/cargo-binstall@main
@@ -43,14 +42,19 @@ jobs:
         run: |
           mkdir -p testcov
           cargo tarpaulin --out Html
-          mv tarpaulin-report.html testcov/index.html
+        
+      - name: Check for tarpaulin-report.html
+        run: |
+          if [ ! -f target/tarpaulin-report.html ]; then
+            echo "tarpaulin-report.html not found!"
+            exit 1
+          fi
 
       - name: Copy files to output directory
         run: |
           mkdir output
-          mkdir -p output/docs
-          cp -r testcov output/
-          cp -r docs output/
+          cp tarpaulin-report.html target/doc/rustframe/
+          cp -r target/doc/* output/
 
       - name: Upload Pages artifact
         # if: github.event_name == 'push'
